---
# tasks file for ansible-role-docker-container-forgejo

- name: docker_image pull {{ docker_image_forgejo_name }}
  community.docker.docker_image:
    name: '{{ docker_image_forgejo_name }}'
    source: pull
    # Select platform for pulling. If not specified, will pull whatever docker prefers.
    pull:
      platform: amd64
  when: 
    - docker_image_forgejo_pull

- name: docker_network {{ docker_container_forgejo_name }}
  community.docker.docker_network:
    name: "{{ docker_network_forgejo_name }}"
    driver: "{{ docker_network_forgejo_driver | default('bridge') }}"
    attachable: "{{ docker_network_forgejo_attachable | default(true) }}"
    enable_ipv6: "{{ docker_network_forgejo_enable_ipv6 | default(false) }}"
    internal: "{{ docker_network_forgejo_internal | default(false) }}"
    state: present


- name: docker_container {{ docker_container_forgejo_name }}
  community.docker.docker_container:
    name: "{{ docker_container_forgejo_name }}"
    comparisons: "{{ docker_container_forgejo_comparisons }}"
    image: "{{ docker_container_forgejo_image }}"
    state: "{{ docker_container_forgejo_state | default('started') }}"
    recreate: "{{ docker_container_forgejo_recreate | default(false) }}"
    restart: "{{ docker_container_forgejo_restart | default(false) }}"
    restart_policy: "{{ docker_container_forgejo_restart_policy | default('always') }}"
    container_default_behavior: no_defaults
    auto_remove: "{{ docker_container_forgejo_auto_remove | default(false) }}"
    detach: "{{ docker_container_forgejo_detach | default(true) }}"
    init: "{{ docker_container_forgejo_init | default(false) }}"
    interactive: "{{ docker_container_forgejo_interactive | default(false) }}"
    keep_volumes: "{{ docker_container_forgejo_keep_volumes | default(true) }}"
    memory: "{{ docker_container_forgejo_memory | default('0') }}"
    paused: "{{ docker_container_forgejo_paused | default(false) }}"
    privileged: "{{ docker_container_forgejo_privileged | default(false) }}"
    read_only: "{{ docker_container_forgejo_read_only | default(false) }}"
    tty: "{{ docker_container_forgejo_tty | default(false) }}"
    env_file: "{{ docker_container_forgejo_env_file | default(omit) }}"
    env: "{{ docker_container_forgejo_env | default(omit) }}"
    volumes: "{{ docker_container_forgejo_volumes | default(omit) }}"
    labels: "{{ docker_container_forgejo_labels | default(omit) }}"
    networks_cli_compatible: "{{ docker_container_forgejo_networks_cli_compatible | default(true) }}"
    network_mode: "{{ docker_network_forgejo_name }}"
    pull: "{{ docker_container_forgejo_pull | default(false) }}"
    networks: "{{ docker_container_forgejo_networks }}"
    published_ports: "{{ docker_container_forgejo_ports | default(omit) }}"
